app = 'hlw-bot'
primary_region = 'ams'

[build]
  dockerfile = 'Dockerfile'

[processes]
  app = 'python bot.py'

[deploy]
  strategy = 'immediate'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
